version: '3.9'

services:

  db:
    image: postgres:15-alpine
    container_name: db-1
    restart: always
    environment:
      POSTGRES_DB: telemetry
      POSTGRES_USER: guikae06
      POSTGRES_PASSWORD: ac_project
    ports:
      - "5432:5432"
    volumes:
      - ./docker/initdb:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8888:8080"

  web:
    build:
      context: .
      dockerfile: docker/php-with-pgsql.Dockerfile
    container_name: web
    restart: always
    volumes:
      - ./Front:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    expose:
      - "9000"
    depends_on:
      - db

  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - "8081:80" # Frontend bereikbaar via http://localhost:8080
    volumes:
      - ./docker/Caddyfile:/etc/caddy/Caddyfile
      - ./Front:/var/www/html
    depends_on:
      - web

volumes:
  pgdata: