version: "3.9"

services:
  webserver:
    image: "caddy:2-alpine"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "$PWD/html:/var/www/html"
      - "$PWD/Caddyfile:/etc/caddy/Caddyfile"
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - cgi
      - db

  cgi:
    build:
      context: "backend"
      dockerfile: "php-with-pgsql.Dockerfile"
    env_file: .env
    volumes:
      - "$PWD/html:/var/www/html"
    depends_on:
      - db

db:
  image: postgres:15-alpine
  environment:
    POSTGRES_DB: telemetry
    POSTGRES_USER: guikae06
    POSTGRES_PASSWORD: ac_project
  ports:
    - "5432:5432"
  volumes:
    - db_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8888:8080"
    depends_on:
      - db

volumes:
  caddy_data:
  caddy_config:
  db_data:

